### ISSUE TITLE
More stats?

### ISSUE THREAD

**Issue by vcvpaiva** [kkalouli/SICK-processing#2]
Can we produce stats of number of lemmas of nouns, verbs, adjs and adverbs, please?

**Comment by vcvpaiva** [comment]
Thanks for the new stats @kkalouli! can we also have the lists of verbs, adjectives, nouns and adverbs, please?

**Comment by vcvpaiva** [comment]
Thanks for the unique lists of verbs, nouns, etc! Sorry, but is it possible and easy to have it (as you have in alphabetical order) but with number of occurrences next? you see the a verb only appears once in the corpus I will give much less attention than if it appears dozens like "play".

 rte-sick/expanded/lemmas/lemmas-VERB.txt
has 513 vs ours 476 but maybe we only have true verbs.

then I promise I will close the issue...

**Comment by kkalouli** [comment]
Sorry, I meant to get the numbers as well but I was doing so many things at the same time yesterday so I just forgot. You can now find a folder "stats" with files with the different occurrences and their numbers. 
I also went ahead and did the general stats for lemmas, forms and deps myself as I have the impression that the UD tools script has a bug. Anyway, you can find these things in the stats folder as well. Please find the updated conllu file in the main folder. 

And one last comment: we have 6076 sentences but 6077 roots because the following sentence gets a wiiiiild parse!!!:

# Two people are in the snow holding two dogs with golden coats . 
1	Two	two	_	CD	_	2	nummod	2:nummod	U
2	people	people	_	NNS	Number=Plur	0	root	_	n07942152:0.4060293534145077,n08160276:0.06300700021191769,n07971141:0.0211863185958663,n08180190:0.009777327777708275|GroupOfPeople=
3	are	be	_	VBP	Tense=Pres	2	dep	2:dep	v02604760:0.3897952239744894,v02616386:0.1233835444837515,v02655135:0.04714120951112247,v02603699:0.025334752712428018,v02749904:0.02105862616544754,v02664769:0.007148761592612987,v02620587:0.010569595235393695,v02445925:0.007481029775364848,v02697725:0.005692013773158934,v02268246:0.0032747360979478893,v02614181:0.003620510307075277,v02744820:0.002763174869068425,v02702508:0.0010731975231470763|Entity+
4	in	in	_	IN	_	5	case	5:case	U
5	the	the	_	DT	Definite=Def	3	nmod	3:nmod:in	U
6	snow	snow	_	NN	Number=Sing	5	root	5:root	n11508382:0.4060293534145077,n15043763:0.06300700021191769,n11307082:0.0211863185958663,n03066743:0.009777327777708275|Snowing+
7	holding	hold	_	VBG	_	6	acl	6:acl	v02681795:0.4275061476260558,v01216670:0.10239860459509084,v01733477:0.048124835954756306,v02203362:0.028503804298845928,v00693780:0.016658823277680767,v01773130:0.009281449578472725,v01301410:0.010197226835054423,v02283324:0.006217169248955373,v02302220:0.004603377618480604,v01217043:0.004749129483935786,v02700867:0.00317157761217778,v02732798:0.0034044436176525372,v02683489:0.002455421413395802,v01601234:0.0024141917523187784,v02648502:7.58869272960102E-4,v00683771:0.001767044172857257,v02746275:0.0014547955037277174,v02701210:0.0012165201105247198,v02498320:0.001384382966011355,v01129876:0.001210912368536296,v00885217:7.156671065460905E-4,v00736586:8.521221513219089E-4,v00607000:4.6772437907461017E-4,v02706816:8.101375466252092E-4,v02676789:4.6840786336243455E-4,v02643574:6.532644725440759E-4,v02510337:6.156221495806456E-4,v02450989:3.2043307247281113E-4,v02441897:5.420187665912608E-4,v01859586:4.8232822032825127E-4,v01334744:4.547135015793968E-4,v01205153:3.1578955095231206E-4,v01151753:4.1583893322583686E-4,v00822367:2.0344889450301623E-4,v00805376:3.8790219565082174E-4,v00004492:1.7288485691958398E-4|Keeping+
8	two	two	_	CD	_	9	nummod	9:nummod	U
9	dogs	dog	_	NNS	Number=Plur	7	dobj	7:dobj	n02084071:0.3974235736313493,n10114209:0.06167156876081363,n10023039:0.02073727521829126,n09886220:0.009570097613152126,n07676602:0.0052531796421179805,n03901548:0.0032179779444162413,n02710044:0.002126327189859401|DomesticDog=
10	with	with	_	IN	_	12	case	12:case	U
11	golden	golden	_	JJ	_	12	amod	12:amod	a00369941:0.5415910355063903,a01149195:0.1643659857917801,a01528730:0.12139859574151185,a00670938:0.020249081547506202,a00300943:0.07754258997300734,a00177547:0.07485271143980436|Brown+
12	coats	coat	_	NNS	Number=Plur	7	nmod	7:nmod:with	n03057021:0.41412747351513096,n03058107:0.06426365382724193,n01898731:0.021608872657627058|Coat=
13	.	_	_	.	_	6	punct	6:punct	U

It indeed has two roots, thus the mismatching of numbers.

**Comment by vcvpaiva** [comment]
many thanks! closing the issue, as I now have plenty of stats to play with!

**Comment by vcvpaiva** [comment]
ps: why do you think the UD script has a bug? if we find evidence we should tell Martin, who's been very helpful in several occasions

**Comment by kkalouli** [comment]
So, now I discovered it precisely: the bug is that you need to add two new lines after the last sentence of the conllu file so that the last sentence gets counted. Otherwise, the last sentence doesnt get counted and you always get one sentence less in the total sentence count and in the roots count of course (and in all other metrics anyway). It shouldnt be the case that you have to add two newlines after the last sentence because the UD format says that you should have only one new line after each sentence. They are also saying themselves (as comment within the script) that every sentence should be followed by a newline, including the last one but this is bug-gy. They could either change the comment within their script so that it says that you need to add two newlines after the last sentence or correct the script itself. I dont have much time to look for the bug myself within the script.
